#!/bin/bash

# --- Resource Requests ---
# Keeping 20 min limit for initial test runs. Increase later for full training.

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4         # Request 4 CPUs (match num_workers in DataLoader)
#SBATCH --gres=gpu:a100           # Request one A100 GPU
#SBATCH --time=00:20:00
#SBATCH --job-name=adni_convnext  # Job name
#SBATCH -o adni_convnext_%j.out   # Standard output log
#SBATCH -e adni_convnext_%j.err   # Standard error log

# --- Your Commands ---
echo "Starting ADNI Training job $SLURM_JOB_ID on $(hostname)"
echo "Loading Conda environment..."

# Activate the conda environment
source ~/miniconda3/bin/activate torch

echo "Conda environment activated. Running Python training script..."

# Run your main training script
python train.py

echo "Job finished"
